### PR TITLE
Throw error when there's a failure to route a mantle message

### PR DESCRIPTION
**Pull request by brandonhilkert**

### CODE REVIEW

**Comment by gammons** [comment]
:+1:

**Comment by TheOddLinguist** [comment]
:+1: Does it make sense to re-raise, or is there no chance anything will ever be able to catch it?

**Comment by brandonhilkert** [comment]
@TheOddLinguist I think the whole process will stop if we do. Ideally, we send to a third-party service that's configurable, but I want to ensure the listener stays up.

**Comment by TheOddLinguist** [comment]
Oh, right. I forgot the context. hehe Carry on.

**Comment by brandonhilkert** [comment]
Only extra question I had was should we log `@channel` and `@message` in the output. Could mean the log could get big fast.

**Pull request merged**
